// subcontractorFormFields.ts
export const subcontractorFormFields = [
  { name: "name", placeholder: "Name", required: "Name is required", type: "text" },
  { name: "registrationNumber", placeholder: "Registration Number", required: "Registration Number is required", type: "text" },
  { name: "addressLine1", placeholder: "Address Line 1", required: "Address Line 1 is required", type: "text" },
  { name: "postcode", placeholder: "Postcode", required: "Postcode is required", type: "text" },

  // Optional fields
  { name: "town", placeholder: "Town (optional)", required: false, type: "text" },
  { name: "country", placeholder: "Country (optional)", required: false, type: "text" },
  { name: "administrativeArea", placeholder: "Administrative Area (optional)", required: false, type: "text" },
  { name: "addressLine2", placeholder: "Address Line 2 (optional)", required: false, type: "text" },
  { name: "addressLine3", placeholder: "Address Line 3 (optional)", required: false, type: "text" },
  { name: "buildingName", placeholder: "Building Name (optional)", required: false, type: "text" },
  { name: "buildingNumber", placeholder: "Building Number (optional)", required: false, type: "text" },
  { name: "county", placeholder: "County (optional)", required: false, type: "text" },
  { name: "deliveryPointSuffix", placeholder: "Delivery Point Suffix (optional)", required: false, type: "text" },
  { name: "departmentName", placeholder: "Department Name (optional)", required: false, type: "text" },
  { name: "dependantLocality", placeholder: "Dependant Locality (optional)", required: false, type: "text" },
  { name: "dependantThoroughfare", placeholder: "Dependant Thoroughfare (optional)", required: false, type: "text" },
  { name: "district", placeholder: "District (optional)", required: false, type: "text" },
  { name: "doubleDependantLocality", placeholder: "Double Dependant Locality (optional)", required: false, type: "text" },
  { name: "eastings", placeholder: "Eastings (optional)", required: false, type: "number" },
  { name: "isRural", label: "Is Rural (optional)", required: false, type: "checkbox" },
  { name: "latitude", placeholder: "Latitude (optional)", required: false, type: "number" },
  { name: "longitude", placeholder: "Longitude (optional)", required: false, type: "number" },
  { name: "northings", placeholder: "Northings (optional)", required: false, type: "number" },
  { name: "organisationName", placeholder: "Organisation Name (optional)", required: false, type: "text" },
  { name: "poBox", placeholder: "PO Box (optional)", required: false, type: "text" },
  { name: "postcodeInwards", placeholder: "Postcode Inwards (optional)", required: false, type: "text" },
  { name: "postcodeOutwards", placeholder: "Postcode Outwards (optional)", required: false, type: "text" },
  { name: "postcodeType", placeholder: "Postcode Type (optional)", required: false, type: "text" },
  { name: "premise", placeholder: "Premise (optional)", required: false, type: "text" },
  { name: "suOrganisationIndicator", placeholder: "SU Organisation Indicator (optional)", required: false, type: "text" },
  { name: "subBuilding", placeholder: "Sub Building (optional)", required: false, type: "text" },
  { name: "thoroughfare", placeholder: "Thoroughfare (optional)", required: false, type: "text" },
  { name: "traditionalCounty", placeholder: "Traditional County (optional)", required: false, type: "text" },
  { name: "udprn", placeholder: "UDPRN (optional)", required: false, type: "text" },
  { name: "umprn", placeholder: "UMPRN (optional)", required: false, type: "text" },
  { name: "ward", placeholder: "Ward (optional)", required: false, type: "text" },
];
